name: compendium_computational_environment
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - snakemake=7.18
  - r=4.1
  - r-tidyverse
  - r-dplyr
  - r-mfp
  - r-haven
  - r-hexbin
  - graphviz
